database in progress
mishacausur/whetherplus pull request #6
Opened 2021-07-13 15:09 UTC by mishacausur

2021-07-13 18:04 UTC, FuzzzzyBoy requested changes

2021-07-15 13:50 UTC, mishacausur commented on WhetherPlus/Network/DataModels/DataBaseModel.swift
> +//    @objc dynamic var daily: [DataBaseDaily]?
убрал

2021-07-15 13:50 UTC, mishacausur commented on WhetherPlus/Network/DataModels/DataBaseModel.swift
> +//}
убрал

2021-07-15 13:50 UTC, mishacausur commented on WhetherPlus/Network/DataModels/DataBaseModel.swift
> +class DataBaseWeather: Object {
убрал это вообще

2021-07-15 13:51 UTC, mishacausur commented on WhetherPlus/Network/DataModels/DataBaseModel.swift
> +class BaseModel: Object {
это я экспериментировал когда только подключил рилм)

2021-07-15 13:54 UTC, mishacausur commented on WhetherPlus/Network/DataModels/DataBaseModel.swift
> +class DataBaseModel: Object {
переименовал

2021-07-15 14:11 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +    }
сделано

2021-07-15 14:12 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +        guard let realm = realm else {
поправил

2021-07-15 14:14 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +        guard let realm = realm else {
перенес

2021-07-15 14:16 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +        forecast.dscrptn = model.description!
убрал опциональность

2021-07-15 14:16 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +    }
удалил

2021-07-15 14:19 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +        forecast.windSpeed = String("\(Int(model.windSpeed!))")
убрал

2021-07-15 14:43 UTC, mishacausur commented on WhetherPlus/Network/Managers/DataBaseManager.swift
> +        forecast.name = model.name!
добавил

2021-07-15 14:43 UTC, mishacausur commented on WhetherPlus/Network/Managers/Location/LocationManager.swift
> +//            }
убрал

2021-07-15 14:43 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +//    let realm = try! Realm()
убрал

2021-07-15 14:44 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +//import RealmSwift
убрал

2021-07-15 14:44 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +    var dataBaseModel: DataBaseModel?
починил

2021-07-15 14:45 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +            self.summaryView.currentTemperatureLabel.text = model.currentTemp ?? ""
я здесь пытался избавиться от опциоальности, но не получилось(

2021-07-15 14:46 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +    private func loadDataBase() {
переименовал

2021-07-15 14:46 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
>          dateFormatter.dateFormat = "dd MMMM"
а как так можно сделать?

2021-07-15 14:46 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +        DispatchQueue.main.async {
хорошо)

2021-07-15 14:48 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
> +        self.dataBaseModel = dataBaseModel
если честно не совсем понимаю как это сделать, ForecastControllerModel же загружает данные из сети, то есть тогда логика предзагрузки данных из БД не будет работать?

2021-07-15 14:52 UTC, mishacausur commented on WhetherPlus/ViewControllers/MainViewController.swift
>                  guard let forecast = data, let hourly = forecast.hourly else {
убрал его из getCurrentDate()

2021-07-15 14:55 UTC, mishacausur commented on WhetherPlus/ViewControllers/PageViewController.swift
> +    init(vc: [UIViewController], name: String?) {
да, без него оказывается все работает - убираю

2021-07-15 14:56 UTC, mishacausur commented on WhetherPlus/ViewControllers/PageViewController.swift
>      let bottomLineView: UIView = {
добавил

2021-07-15 14:57 UTC, mishacausur commented on WhetherPlus/ViewControllers/PageViewController.swift
> +    }
удалил

2021-07-15 14:57 UTC, mishacausur commented on WhetherPlus/ViewControllers/PageViewController.swift
> +//            vc.summaryView.cloudsLabel.text = i.pop + " мм"
убрал

2021-07-18 18:27 UTC, FuzzzzyBoy requested changes

2021-08-29 11:54 UTC, merged