Onedayvc
mishacausur/whetherplus pull request #7
Opened 2021-08-15 09:38 UTC by mishacausur

2021-08-18 15:34 UTC, FuzzzzyBoy requested changes

2021-08-19 14:02 UTC, mishacausur commented on WhetherPlus/AppCoordinator.swift
> +    var updater: UpdateViewWithSettingsCompletion?
переименовал

2021-08-19 14:04 UTC, mishacausur commented on WhetherPlus/ViewControllers/ForecastControllerViewModel.swift
> +    var completion: (()->())?
убрал

2021-08-19 14:05 UTC, mishacausur commented on WhetherPlus/ViewControllers/ForecastControllerViewModel.swift
> +        guard let forecast = forecastModel else {return}
убрал

2021-08-19 14:06 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +                dayView.alpha = 1
поправил

2021-08-19 14:15 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private func configureDayView(daily: Daily?) {
перенес, убрал опшнл

2021-08-19 14:17 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private lazy var dailyCollection: UICollectionView = {
так мы вроде всегда коллекции и таблицы на вк делали, а уже их ячейки выносили в отдельные вьюшки, а тут надо саму коллекцию вынести в отдельный файл?

2021-08-19 14:18 UTC, mishacausur commented on WhetherPlus/Views/DescribeOneDayView.swift
> +class DescribeOneDayView: UIView {
переименовал

2021-08-19 19:40 UTC, FuzzzzyBoy commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private lazy var dailyCollection: UICollectionView = {
одно другому не мешает )). Можно и коллекцию вынести в отдельную сущность, и ячейки в ней тоже сделать отдельными сущностями, если они достаточно сложные. В этом view controller уже много логики по размещению всех сабвью, лучше разгрузить его от работы с коллекцией

2021-08-21 12:34 UTC, mishacausur commented on WhetherPlus/Views/OneDayView.swift
> +        view.iconLabel.text = "Облачность"
сделал

2021-08-21 15:54 UTC, mishacausur commented on WhetherPlus/Views/OneDayView.swift
> +        let constraints = [
сделал

2021-08-21 18:25 UTC, FuzzzzyBoy commented on WhetherPlus/Views/OneDayView.swift
> +        let feelsLikeData = SunAndMoonDesribingViewData(image: "grad", characteristic: "По ощущениям", value: String(describing: Int(daily.feelsLike.day)) + "\u{00B0}")
Вижу у тебя часто использование String(describing: ...). Это не ошибка, но в большинстве случаев в этом проекте вариант "\(Int(daily.feelsLike.day)) + \u{00B0}" более стандартный

2021-08-21 18:35 UTC, FuzzzzyBoy commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +                dayView.configureStackViewData(daily: daily)
Лучше у OneDayView сделать один метод configure(with daily: Daily) и OneDayView сам разберется как настроить свои сабвью - это облегчит использование OneDayView

2021-08-21 18:35 UTC, FuzzzzyBoy commented on WhetherPlus/Views/OneDayView.swift
> +           switch whether {
не в рамках этого PR, но для weather напрашивается использование enum

2021-08-21 19:53 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private lazy var dailyCollection: UICollectionView = {
перенес

2021-08-28 10:10 UTC, FuzzzzyBoy commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private func configureSunView(daily: Daily?) {
можно в SunAndMoonView добавить метод configure(with daily: Daily) и перенести код из этого метода

2021-08-28 10:10 UTC, FuzzzzyBoy commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        DispatchQueue.main.async { [self] in
точно тут везде нужен DispatchQueue.main.asynс?

2021-08-28 10:12 UTC, FuzzzzyBoy commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        moonView.firstLineView.addDashedBorder(strokeColor: UIColor(named: "Accent Blue")!, lineWidth: 0.5)
код для sunView и moonView дублируется, лучше этого избегать. Можно в отдельный метод вынести или через [sunView, moonView].forEach { ... } сделать

2021-08-28 10:17 UTC, FuzzzzyBoy commented on WhetherPlus/Views/DailyCollection.swift
> +         dailyCollection.bottomAnchor.constraint(equalTo: self.bottomAnchor)].forEach { $0.isActive = true }
Вместо forEach можно использовать метод NSLayoutConstraint.activate, он так же активирует все констрейнты, которые в него передаешь

2021-08-28 10:18 UTC, FuzzzzyBoy commented on WhetherPlus/Views/DailyCollection.swift
> +        guard let dailyCount = daily?.count else { return 1 }
а почему 1 возвращаешь, а не 0?

2021-08-28 10:20 UTC, FuzzzzyBoy commented on WhetherPlus/Views/DailyCollection.swift
> +    var completion: ((Daily)->())?
имя очень абстрактное, непонятно когда этот completion вызывается

2021-08-28 10:21 UTC, FuzzzzyBoy commented on WhetherPlus/Views/OneDayView.swift
> +    func configureNightView(daily: Daily?) {
в configureDayView и configureNightView много дублирующегося кода

2021-08-29 09:06 UTC, mishacausur commented on WhetherPlus/Views/DailyCollection.swift
> +         dailyCollection.bottomAnchor.constraint(equalTo: self.bottomAnchor)].forEach { $0.isActive = true }
я везде делаю через NSLayoutConstraint.activate а тут решил поэкспериментировать))

2021-08-29 09:07 UTC, mishacausur commented on WhetherPlus/Views/DailyCollection.swift
> +        guard let dailyCount = daily?.count else { return 1 }
поправил

2021-08-29 09:10 UTC, mishacausur commented on WhetherPlus/Views/DailyCollection.swift
> +    var completion: ((Daily)->())?
переименовал

2021-08-29 09:13 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        moonView.firstLineView.addDashedBorder(strokeColor: UIColor(named: "Accent Blue")!, lineWidth: 0.5)
реализовал

2021-08-29 09:20 UTC, mishacausur commented on WhetherPlus/Views/OneDayView.swift
> +    func configureNightView(daily: Daily?) {
добавил еще одну функцию с дублирующим кодом

2021-08-29 09:21 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        DispatchQueue.main.async { [self] in
а как? там же UI затрагивается

2021-08-29 09:22 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        DispatchQueue.main.async { [self] in
хотя работает без этого

2021-08-29 09:24 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +        DispatchQueue.main.async { [self] in
убрал

2021-08-29 09:39 UTC, mishacausur commented on WhetherPlus/ViewControllers/OneDayViewController.swift
> +    private func configureSunView(daily: Daily?) {
переделал

2021-08-29 09:41 UTC, mishacausur commented on WhetherPlus/Views/OneDayView.swift
> +        let feelsLikeData = SunAndMoonDesribingViewData(image: "grad", characteristic: "По ощущениям", value: String(describing: Int(daily.feelsLike.day)) + "\u{00B0}")
а Xcode все время хочет чтобы я заменил на String(describing: ...)

2021-08-29 11:51 UTC, mishacausur commented on WhetherPlus/Views/SunAndMoonView.swift
> +        let constraints = [
сделал, но пропала пунктирная линия

2021-08-29 11:53 UTC, merged